{
  "formatVersion": "1.1",
  "component": {
    "group": "net.md-5",
    "module": "bungeecord-chat",
    "version": "1.20-R0.2-deprecated+build.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "21.0"
          }
        }
      ],
      "files": [
        {
          "name": "bungeecord-chat-1.20-R0.2-deprecated+build.18.jar",
          "url": "bungeecord-chat-1.20-R0.2-deprecated+build.18.jar",
          "size": 158696,
          "sha512": "0d860a43aca6e9fb8f9d487f9eca4c0a4f8dce09eab71d41053dacc35f1b96c0019860705f53a30b17f9ece11a7912255162b7e4ac40ac1a8f909c09dea5b89a",
          "sha256": "5e61313bb35aae1b2be33276ab442f6e0d56258ff13297750d6ad9484d1a4fd6",
          "sha1": "5035a741a44c35d9284251413050dc6470c09978",
          "md5": "915fa22e4f0b9f322c1e31752449a004"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "21.0"
          }
        }
      ],
      "files": [
        {
          "name": "bungeecord-chat-1.20-R0.2-deprecated+build.18.jar",
          "url": "bungeecord-chat-1.20-R0.2-deprecated+build.18.jar",
          "size": 158696,
          "sha512": "0d860a43aca6e9fb8f9d487f9eca4c0a4f8dce09eab71d41053dacc35f1b96c0019860705f53a30b17f9ece11a7912255162b7e4ac40ac1a8f909c09dea5b89a",
          "sha256": "5e61313bb35aae1b2be33276ab442f6e0d56258ff13297750d6ad9484d1a4fd6",
          "sha1": "5035a741a44c35d9284251413050dc6470c09978",
          "md5": "915fa22e4f0b9f322c1e31752449a004"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "bungeecord-chat-1.20-R0.2-deprecated+build.18-sources.jar",
          "url": "bungeecord-chat-1.20-R0.2-deprecated+build.18-sources.jar",
          "size": 43906,
          "sha512": "8e78722f0b106cbc530e71e19fdc58dbfcfae0791027808384969e54bf0df0d91be1df62538c126b51c89007b12ffc498cc85e74863939673937c209c9fc1a31",
          "sha256": "59d7814f86c59f0b5efbcedf426bb66bbdd4c68274edfa5620cc602d52baedad",
          "sha1": "9b231e49c232114046a0ef1c0044f2a01e817d25",
          "md5": "ddfb431dc96d656d46eed56e061fda2c"
        }
      ]
    }
  ]
}
