{
  "formatVersion": "1.1",
  "component": {
    "group": "net.kyori",
    "module": "adventure-text-minimessage",
    "version": "4.17.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.17.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.17.0"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-text-minimessage-4.17.0.jar",
          "url": "adventure-text-minimessage-4.17.0.jar",
          "size": 160889,
          "sha512": "81e4e939b3de81d6ef8f46f310739db3b1f0c9bd1f26649422071ff63eae0bc0fda5b05ad9cbdb56c8b6f72b3956851167d9e641cc16064af4c57b08b37a19f7",
          "sha256": "8372a9e9bc0c0ae21d60e6ce6e284a81c6c96d1ec398f808825015c6f60252f5",
          "sha1": "696817a0f9700483bcd9dbd5cc62f33ac83b12f9",
          "md5": "54ad32833bd33cc202ba1041e246e006"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.17.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.17.0"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-text-minimessage-4.17.0.jar",
          "url": "adventure-text-minimessage-4.17.0.jar",
          "size": 160889,
          "sha512": "81e4e939b3de81d6ef8f46f310739db3b1f0c9bd1f26649422071ff63eae0bc0fda5b05ad9cbdb56c8b6f72b3956851167d9e641cc16064af4c57b08b37a19f7",
          "sha256": "8372a9e9bc0c0ae21d60e6ce6e284a81c6c96d1ec398f808825015c6f60252f5",
          "sha1": "696817a0f9700483bcd9dbd5cc62f33ac83b12f9",
          "md5": "54ad32833bd33cc202ba1041e246e006"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.17.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.17.0"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-text-minimessage-4.17.0-javadoc.jar",
          "url": "adventure-text-minimessage-4.17.0-javadoc.jar",
          "size": 382135,
          "sha512": "31527a63f187d130419baf93557b6c6cf800e37732899be74664c2377d15e6ddab46384434b4fffa8cfda081eede52b611cd440c90aca30fa3ead47e8c228683",
          "sha256": "97261c41064c8628822ac9366ffb049209816110e3ba3e7b7aa4fb2d7ba9d6cd",
          "sha1": "5bf81c4e6ec94b02c967aa97b457ba5f9ce613f3",
          "md5": "455db2c3848a495e6d0ab3981973831d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "adventure-text-minimessage-4.17.0-sources.jar",
          "url": "adventure-text-minimessage-4.17.0-sources.jar",
          "size": 144256,
          "sha512": "d8f19ac6bd020b4e6f145dee49631b2b343663c6b6d601750fbd277df16b84bcd91eb91efb222eb9587f0bed79ae7a898db99083e611de0aed288c603e06af2c",
          "sha256": "d82698980c6ccd63253c0fa461e607e07c72c33158a65c832c4bb00de4064903",
          "sha1": "adb7d94422a164f198dd19d69e245fac7b0eab53",
          "md5": "3d1d2c8e34d8db475ca75061dd77d983"
        }
      ]
    }
  ]
}
